name: Website Screenshot

on: [deployment_status]


jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Screenshot
        uses: alexrogalskiy/github-action-screenshots@master
        with:
          url: "https://alpaca-image-generator-sigma.vercel.app"
          name: 'project-screenshot'
          path: 'public'
          width: 1280
          height: 720
          
      - name: Commit
        run: |
          git config --local user.email 'github-actions@github.com'
          git config --local user.name 'GitHub Action'
          git add --all
          git commit -m 'Update Preview'
          git push
