name: Website Screenshot

on: [deployment_status]


jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Screenshot Website
      uses: AlexRogalskiy/github-action-screenshots@2.0.1
      with:
        # screenshot source url
        url: https://alpaca-image-generator-sigma.vercel.app
        # screenshot name
        name: project-screenshot.png
        # screenshot path
        path: public
