name: Website Screenshot

on: [deployment_status]


jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Screenshot Website
      uses: JonathanTreffler/full-website-screenshot-action@v1.0
      with:
        url: https://alpaca-image-generator-sigma.vercel.app
        destination: ./screenshot.png
