name: Website Screenshot

on: [deployment_status]


jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://alpaca-image-generator-sigma.vercel.app
        destination: screenshot.png